# Generated by Django 5.1.4 on 2025-01-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerscount',
            old_name='follwer',
            new_name='follower',
        ),
    ]
