# Generated by Django 5.1.4 on 2025-02-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_follwer_followerscount_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(blank=True, default='blank-profile-picture.jpg', null=True, upload_to='profile_images'),
        ),
    ]
